### PR TITLE
Fix for blurry rendering of images when scale factor is fractional

### PR DESCRIPTION
**Pull request by bosim**
Fixes issue #242

### CODE REVIEW

**Comment by tsujan** [comment]
The problem is deeper than scaling the cached image (you could see it with gif animations too — they aren't cached) and increasing the scale factor doesn't solve it.

Please wait until https://github.com/lxqt/lximage-qt/pull/252 is merged (because of conflicts) and then we'll discuss it

**Comment by tsujan** [comment]
@agaida Please don't merge it -- it'll be superseded by a working PR.

**Comment by bosim** [comment]
> @agaida Please don't merge it -- it'll be superseded by a working PR.

I will close if you are working on a solution that will cover it all.

**Comment by tsujan** [comment]
> I will close if you are working on a solution that will cover it all.

The solution is ready but should wait a little because of PR conflicts.

**Pull request closed without merging**
