### PR TITLE
Add preference option to deactivate image changing by mouse wheel

### PR DESCRIPTION
**Pull request by bosim**
I do not find that feature useful so added an option to turn it off.

### CODE REVIEW

**Comment by tsujan** [comment]
@agaida Please don't merge this for now (the code will change because of a previous PR and an upcoming one and their rebasing wouldn't be easy).

**Comment by tsujan** [comment]
Please update your patch for it to be merged! Specifically, `preferencesdialog.ui` needs to be corrected because it has changed. Other things seem OK.

**Comment by int-ua** [comment]
#281

**Comment by bosim** [comment]
@tsujan I will rework this PR, closing it for now.

**Pull request closed without merging**
