### PR TITLE
 Reorganize preferences dialog 

### PR DESCRIPTION
**Pull request by xiota**
Proposed reorganization of preferences.

screenshot-08-preferences

### CODE REVIEW

**Comment by tsujan** [comment]
Please:

 1. Don't touch `settings.cpp`! Changing groups is backward incompatible and we avoid that in LXQt. Moreover, there's no need to a correspondence between Preferences dialog and config file. The former is for the user, while the latter is for the app.
 2. Don't drop "by default". It means "when the app starts". The changes made to the main window are temporary and that's a feature we don't want to remove.

**Comment by xiota** [comment]
I put `settings.cpp` back to how it was before except that I moved `ShowExifData` to the `Windows` section.  It was in the `Thumbnails` section before, and the people this change affects should be limited since it was added only recently.

I put "by default" back.  It just seemed redundant because the preferences dialog should naturally affect the default. It's also repetitive, appearing in so many options right next to each other.

**Comment by tsujan** [comment]
> The preferences dialog should naturally affect the default.

When an option says, for example, "Show main toolbar", its unchecking should remove the toolbar immediately or after closing the Preferences dialog (preferably, the first). But when it says, "Show main toolbar by default", the user knows it changes a default behavior.

**Comment by tsujan** [comment]
I tested it. I'm afraid it seems to me like too many tabs for a few options.

We need a third opinion. @stefonarch, would you please test it and see if you like its Preferences dialog?

**Comment by xiota** [comment]
Maybe Thumbnails could be combined with Image.  Image will become crowded later though.

Or maybe Thumbnails could go with General.

**Comment by tsujan** [comment]
Let's wait for @stefonarch!

**Review by tsujan — APPROVED** [review]
This is much better. Thanks!

**Comment by xiota** [comment]
Glad you like this better.  Let me know when you feel like looking at any other PRs.  Also, what's your opinion of using Exiv2 instead of libexif or as a compile-time selection?  Reason I'm thinking about it is Exiv2 supports more file types.

**Comment by stefonarch** [comment]
> Let's wait for @stefonarch!
> 
> EDIT: I asked @stefonarch's opinion on 5 tabs; didn't notice that they're 4 now.

Sorry if I missed something, but it isn't easy to track so many GH notifications. Preferences look good now.

**Comment by tsujan** [comment]
> but it isn't easy to track so many GH notifications.

I use Thunderbird and filter LXQt mails, so that they go to an LXQt folder.

**Comment by stefonarch** [comment]
> > but it isn't easy to track so many GH notifications.
> 
> I use Thunderbird and filter LXQt mails, so that they go to an LXQt folder.

I do so too, but when there are >30 in the morning I prefer to overfly the conversation on GH and  looks I missed something.  I thought about an additional filter for @stefonarch ...

**Comment by tsujan** [comment]
> ... but when there are >30 in the morning...

It happens here too. Most of them are Weblate translation notifications — "Translations update from Weblate" as a filter might make it better for you.

**Comment by stefonarch** [comment]
I've a filter for them too, they doesn't get mixed witnthe rest. But last days just _lxqt_ was quite busy :)

**Comment by xiota** [comment]
@stefonarch

> But last days just lxqt was quite busy :)

If that was from me, I will slow down soon.

**Comment by tsujan** [comment]
> If that was from me,

No one needs to worry about notifications. Of course, it's good practice not to write everything that comes to one's mind as a comment but your comments haven't been of that sort.

Concise comments are always preferable. Rarely, some people write short stories, instead of reports.

**Pull request merged**
