### PR TITLE
Added resize image feature

### PR DESCRIPTION
**Pull request by adjamhub**
Add an action to enable image resizing.
The feature is based on Gwenview code about.

### CODE REVIEW

**Comment by tsujan** [comment]
I'll review it after the next release.

**Comment by adjamhub** [comment]
Ok,
Thanks.
Have a nice day.

--

Andrea Diamantini

WEB:
https://www.adjam.org/

Computer Science is not about machines, like Astronomy is not about telescopes.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Il mercoledì 22 aprile 2020 17:18, tsujan <notifications@github.com> ha scritto:

**Comment by adjamhub** [comment]
I removed the icon as you requested. I'm having it in my preferred iconset (papyrus) and I saw it used on gwenview. That's because I added it; not a problem anyway.
Fixed style (at least I hope so).
Cannot properly manage GIF and SVG save, so I'm blocking resize action there. If you prefer a different behavior, just let me know.

**Comment by adjamhub** [comment]
Sorry. Closed by accident...

**Comment by tsujan** [comment]
> Fixed style (at least I hope so).

It's good enough.

> Cannot properly manage GIF and SVG save, so I'm blocking resize action there. If you prefer a different behavior, just let me know.

Exporting SVG to greater sizes is an important part of a resize functionality and shouldn't be excluded artificially.

I'll look into it if I find the time.

**Comment by tsujan** [comment]
@adjamhub 

Please change the whole `on_actionResize_triggered` to this:
```c++
void MainWindow::on_actionResize_triggered() {
  if(image_.isNull()) {
    return;
  }
  QGraphicsItem *imageItem = getImageGraphicsItem();
  bool isSVG(dynamic_cast<QGraphicsSvgItem*>(imageItem));
  bool isGifOrSvg(imageItem->isWidget() || isSVG);
  QSize imgSize(image_.size());
  ResizeImageDialog *dialog = new ResizeImageDialog(this);
  dialog->setOriginalSize(image_.size());
  if (dialog->exec() == QDialog::Accepted) {
    QSize newSize = dialog->size();
    if(!isSVG) {
      image_ = image_.scaled(newSize, Qt::IgnoreAspectRatio, Qt::SmoothTransformation);
      ui.view->setImage(image_, isGifOrSvg ? false : true);
    }
    if(isGifOrSvg) {
      qreal sx = static_cast<qreal>(newSize.width()) / imgSize.width();
      qreal sy = static_cast<qreal>(newSize.height()) / imgSize.height();

      QTransform transform;
      transform.scale(sx, sy);
      // we need to apply transformations in the reverse order
      QTransform prevTrans = imageItem->transform();
      imageItem->setTransform(transform, false);
      imageItem->setTransform(prevTrans, true);
      // apply transformations to the outline item too
      if(QGraphicsItem *outlineItem = getOutlineGraphicsItem()) {
        outlineItem->setTransform(transform, false);
        outlineItem->setTransform(prevTrans, true);
      }

      if(isSVG) {
        // create and set a sharp scaled image with SVG
        QPixmap pixmap(newSize.width(), newSize.height());
        pixmap.fill(Qt::transparent);
        QPainter painter(&pixmap);
        painter.scale(sx,sy);
        painter.setRenderHint(QPainter::Antialiasing);
        QStyleOptionGraphicsItem opt;
        imageItem->paint(&painter, &opt);
        image_ = pixmap.toImage();
        ui.view->setImage(image_, false);
      }
    }

    setModified(true);
  }
  dialog->deleteLater();
}
```
This will give sharp images when SVG images are scaled and saved as PNG, JPG, etc. It'll make lximage-qt a very useful tool with SVG images.

**Comment by adjamhub** [comment]
Ok,
this works for resizing. What about saving?

--

Andrea Diamantini

WEB:
https://www.adjam.org/

Computer Science is not about machines, like Astronomy is not about telescopes.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Il domenica 17 maggio 2020 14:50, tsujan <notifications@github.com> ha scritto:

**Comment by tsujan** [comment]
It resizes SVG so that It can be saved as a *sharp* PNG/JPG... image -- that was the goal. lximage-qt never supported saving to SVG or GIF because `QImage::save()` doesn't support that.

https://github.com/lxqt/lximage-qt/pull/325 will inform users about which formats cannot be used while saving.

**Comment by tsujan** [comment]
There's still a small hidden problem. I might merge this PR as it is and fix it in another PR.

**Comment by tsujan** [comment]
The fix is in https://github.com/lxqt/lximage-qt/pull/326, which also contains code cleanups, some of which are related to this PR, some not.

**Pull request merged**
