### PR TITLE
Qt6 port

### PR DESCRIPTION
**Pull request by tsujan**

### CODE REVIEW

**Comment by stefonarch** [comment]
* Bump copyright version in "about".
*  Open file/folder: only navigation in the left pane, no folder displayed on the right
But when a file is once opened clicking in pcmanfm-qt using cltr+o folder content will be displayed but folders cannot be opened. Same with "Save (as)"

**Comment by tsujan** [comment]
> Bump copyright version in "about".

Will do. Thanks.

> Open file/folder: only navigation in the left pane, no folder displayed on the right

I didn't understand this. Which left pane? Could you explain it with a screenshot?

**Comment by stefonarch** [comment]
screen_area_ven_21:16:59_

**Comment by tsujan** [comment]
That's LXQt file dialog, not lximage-qt. There's definitely a weird problem there, but it doesn't exist here. Do you have any clue how it could have happened?

**Comment by stefonarch** [comment]
Yes: 

```
libfm-qt$ git status
On branch app_chooser_restore

```

**Comment by tsujan** [comment]
> Yes:
> 
> ```
> libfm-qt$ git status
> On branch app_chooser_restore
> ```

But that's the Qt5 version of `libfm-qt`, while this branch needs https://github.com/lxqt/libfm-qt/pull/778 (otherwise, it couldn't be compiled).

**Comment by stefonarch** [comment]
It compiled well - that's strange yes
Now recompiled against` libfm-qt_wip_qt6` but it's still the same.

**Comment by tsujan** [comment]
> It compiled well - that's strange yes

It was compiled because you already had `libfm-qt6` (you couldn't compile it against anything else). The problem may be in your `libfm-qt6`. If so, should be able to see the same problem in any Qt6 app that calls LXQt file dialog.

**Comment by tsujan** [comment]
Are you sure that the Qt5 version of lximage-qt isn't running somewhere? Did you install this branch over the Qt5 version or only run it from the build folder?

**Comment by stefonarch** [comment]
Reloaded even the session. Installed over the qt5 version. No issue elsewhere with the filedialog.

**Comment by tsujan** [comment]
I have no idea how such a thing can happen. Here, everything Qt6 is normal:

qt6_lximage-qt

**Comment by stefonarch** [comment]
No idea too. Tested under Plasma, where the Qt file dialog is used apparently, all ok.
It has to be something on my side, will look into it tomorrow.

**Comment by stefonarch** [comment]
All good, went now over my wip_qt6 branches and found `lxqt-qtplugin` not updated.
screen_area_sab_07:36:12_

**Comment by tsujan** [comment]
Any objection to merging? It has been used, tested and completed for more than a year.

**Pull request merged**
